{% set name = "msgpack" %}
{% set version = "1.4.5" %}

package:
  name: rb-{{ name|lower }}
  version: {{ version }}

source:
  url: https://rubygems.org/downloads/{{ name }}-{{ version }}.gem
  sha256: 45048ca94aa2744d9f86fce6943d85f9c18185c212fb9e86e9ef5638ba7e50b3

build:
  number: 0
  script:
    - gem install -N -l -V --norc --ignore-dependencies {{ name }}-{{ version }}.gem
    - gem unpack {{ name }}-{{ version }}.gem
    - make -C {{ PREFIX }}/lib/ruby/gems/{{ ruby }}.0/gems/{{ name }}-{{ version }}/ext/{{ name }} clean
  skip: {{ win }}
  skip: true  # [ruby == "2.5" and osx]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - ruby
  run:
    - {{ pin_compatible('ruby', max_pin='x.x') }}

test:
  commands:
    - ruby -r {{ name }} -e 'exit 0'

about:
  home: https://rubygems.org/gems/{{ name }}
  license: Apache-2.0
  license_family: APACHE
  license_file: {{ name }}-{{ version }}/LICENSE
  summary: |
    MessagePack is a binary-based efficient object serialization library.
    It enables to exchange structured objects between many languages like JSON.
    But unlike JSON, it is very fast and small.
  doc_url: https://www.rubydoc.info/gems/{{ name }}
  dev_url: https://github.com/msgpack/msgpack-ruby

extra:
  recipe-maintainers:
    - mxr-conda
    - sodre
