travis:
  secure:
    BINSTAR_TOKEN: S7wau946jvFOw56jwFOiRXIfwtZL/LSvtZUtx0cQOhgBgKV354fqruPduiIe8gy00/SB5VM02aezqAVv8Eu5uUzHF50xmVG93MP0TxbPtQF194A3tGak4+bCK7Rv89VUVTdmLueY4F2fdMoQowtIqS8Zt56/ZPt+VsbIoZq24bd1USE39Qj2gtNLi7g0/1b+J5dtZaUhrC1IYqyWeMEoMlx46K9w9TO9dA0SIIx/vyYQszhyUgxpdr3Sqt8x3gQ8XNZyFGdnxqvf2O5+pz3P4v+7pIohyTnF6OzDuvEfjS/VFe22gYWh/EqT/00psA3GSTswVY9T6Al5RdRiDyJYfOyRQ7IgyOAcDrs8SIWaHM9sNBSfuhS7icOoL4E3JoF9Ms+gAf/hzjibLFr8ruTI7PHpLjLHPSVW6Qoop80gKGy1MaZWTWP2/c1hnJKpDvddlmc8/tMZNcdf0hABxbQf+uJWxPlBus1g+NsVnnRxBQNT5TnWlE5d/1/F2H6k9a3OAi+a6cwSOVPqX8Mc30IVT01IDBNIWw/eSZsIFQ+xiMuIAtM8FwhMIRtArbr3Q3/mLAX9cF4XeB4Z40VX5egvdqVh8IUv14KON4IMjePUCCftA6BIhYPN91fPvxziUcMEDVv3kWeaiHmUEqrglYDixGhhWZ0sY5bISdhuMWrfaS8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
